<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_wa74gKEGEe-aYLU-FfmCmw" name="ProcessEngine" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_g90NwKEHEe-aYLU-FfmCmw" documentation="&#xD;&#xA;" name="Workflow Engine" displayName="Workflow Engine">
      <elements xmi:type="process:Lane" xmi:id="_iaXEQKEHEe-aYLU-FfmCmw" name="Automatisch"/>
      <elements xmi:type="process:Lane" xmi:id="_lSr8QKEHEe-aYLU-FfmCmw" name="OKR-Facilitator" actor="_AgRgMKEOEe-aYLU-FfmCmw">
        <elements xmi:type="process:Task" xmi:id="_u2bt8KEIEe-aYLU-FfmCmw" name="OKR-Cycle starten" outgoing="_zzxiAKLGEe-pXblqnP0p3A" incoming="_g5B2gKHaEe-aYLU-FfmCmw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WCi9kqEIEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WCi9kaEIEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WCi9k6EIEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WCi9lKEIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WCi9laEIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WCi9lqEIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WCi9mKEIEe-aYLU-FfmCmw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WCi9l6EIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_u2cVAKEIEe-aYLU-FfmCmw">
            <targetForm xmi:type="expression:Expression" xmi:id="_u2cVAaEIEe-aYLU-FfmCmw" name="startForm" content="fc530310-7899-4b6a-843e-8eff8972a264" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_u2bt-aEIEe-aYLU-FfmCmw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_u2cVAqEIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_vrGFEKEIEe-aYLU-FfmCmw" name="Einladung für Drafting verschicken" outgoing="_N6sjYKLOEe-YhYlYVX9NAA" incoming="_zzxiAKLGEe-pXblqnP0p3A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jyNykqEIEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jyNykaEIEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jyNyk6EIEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_yGXi06K3Ee-pXblqnP0p3A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yGXi1KK3Ee-pXblqnP0p3A" name="einladung" content="einladung" type="TYPE_VARIABLE" returnType="com.company.model.Einladung">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yGXi1aK3Ee-pXblqnP0p3A" name="einladung" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.Einladung"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yGXi1qK3Ee-pXblqnP0p3A" name="einladungInput.datum" content="einladungInput?.datum" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDateTime">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ihPDMKLGEe-pXblqnP0p3A" name="einladungInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yGXi2KK3Ee-pXblqnP0p3A" type="JAVA_METHOD" expression="setDatum">
              <inputTypes>java.time.LocalDateTime</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jyNylKEIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jyNylaEIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jyNylqEIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jyNymKEIEe-aYLU-FfmCmw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jyNyl6EIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_vrGsKaEIEe-aYLU-FfmCmw">
            <targetForm xmi:type="expression:Expression" xmi:id="_Tfqr4KHeEe-aYLU-FfmCmw" name="einladungVerschickenForm" content="231d037a-1b3c-4005-8419-0b9b3781cb0d" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_vrGsKKEIEe-aYLU-FfmCmw">
            <inputs xmi:type="process:ContractInput" xmi:id="_yGXi0KK3Ee-pXblqnP0p3A" name="einladungInput" type="COMPLEX" dataReference="einladung">
              <inputs xmi:type="process:ContractInput" xmi:id="_yGXi0aK3Ee-pXblqnP0p3A" name="datum" type="LOCALDATETIME"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_yGXi0qK3Ee-pXblqnP0p3A" expression="einladungInput?.datum != null" errorMessage="datum is mandatory for Einladung" name="mandatory_einladungInput_datum">
              <inputNames>einladungInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_vrGsK6EIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_goVIEKHaEe-aYLU-FfmCmw" name="Start1" outgoing="_g5B2gKHaEe-aYLU-FfmCmw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_goVIEqHaEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_goVIEaHaEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_goVIE6HaEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_CC-WAKKjEe-pXblqnP0p3A" name="End1" incoming="_60LjMKRGEe-hA-m3F63kgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CDHf8aKjEe-pXblqnP0p3A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CDHf8KKjEe-pXblqnP0p3A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_CDHf8qKjEe-pXblqnP0p3A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_I2qwMKLLEe-YhYlYVX9NAA" name="OKRs zuweisen" outgoing="_I28dAKLLEe-YhYlYVX9NAA" incoming="_q9u1cKQmEe-e_PUYJW9ZgA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_I2vBoaLLEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_I2vBoKLLEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_I2vBoqLLEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_YhM2RKQGEe-e_PUYJW9ZgA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_YhM2RaQGEe-e_PUYJW9ZgA" name="okr" content="okr" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_YhM2RqQGEe-e_PUYJW9ZgA" name="okr" multiple="true" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKR"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_YhM2R6QGEe-e_PUYJW9ZgA" name="okrInput" content="def oKRList = []&#xD;&#xA;//For each item collected in multiple input&#xD;&#xA;     .each{&#xD;&#xA;&#x9;//Add OKR instance&#xD;&#xA;&#x9;oKRList.add({ currentOKRInput ->&#xD;&#xA;&#x9;&#x9;def oKRVar = okr.find { it.persistenceId.toString() == currentOKRInput.persistenceId_string} ?: new com.company.model.OKR()&#xD;&#xA;&#x9;&#x9;oKRVar.fortschritt = currentOKRInput.fortschritt&#xD;&#xA;&#x9;&#x9;oKRVar.zustaendig = currentOKRInput.zustaendig&#xD;&#xA;&#x9;&#x9;return oKRVar&#xD;&#xA;&#x9;}(it))&#xD;&#xA;}&#xD;&#xA;return oKRList" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_sWjWoKQzEe-e_PUYJW9ZgA" name="okr" multiple="true" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKR"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_YhM2SqQGEe-e_PUYJW9ZgA" type="ASSIGNMENT" expression="addAll">
              <inputTypes>java.util.Collection</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yakJuqRCEe-hA-m3F63kgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yakJu6RCEe-hA-m3F63kgQ" name="okrTable" content="okrTable" type="TYPE_VARIABLE" returnType="com.company.model.OKRTabelle">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yakJvKRCEe-hA-m3F63kgQ" name="okrTable" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKRTabelle"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yakJvaRCEe-hA-m3F63kgQ" name="okrTableInput.objective1" content="okrTableInput?.objective1" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yakJvqRCEe-hA-m3F63kgQ" name="okrTableInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yakJv6RCEe-hA-m3F63kgQ" type="JAVA_METHOD" expression="setObjective1">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yakJwKRCEe-hA-m3F63kgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yakJwaRCEe-hA-m3F63kgQ" name="okrTable" content="okrTable" type="TYPE_VARIABLE" returnType="com.company.model.OKRTabelle">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yakJwqRCEe-hA-m3F63kgQ" name="okrTable" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKRTabelle"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yakJw6RCEe-hA-m3F63kgQ" name="okrTableInput.zustaendigkeit1" content="okrTableInput?.zustaendigkeit1" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yakJxKRCEe-hA-m3F63kgQ" name="okrTableInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yakJxaRCEe-hA-m3F63kgQ" type="JAVA_METHOD" expression="setZustaendigkeit1">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yakJxqRCEe-hA-m3F63kgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yakJx6RCEe-hA-m3F63kgQ" name="okrTable" content="okrTable" type="TYPE_VARIABLE" returnType="com.company.model.OKRTabelle">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yakJyKRCEe-hA-m3F63kgQ" name="okrTable" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKRTabelle"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yakJyaRCEe-hA-m3F63kgQ" name="okrTableInput.objective2" content="okrTableInput?.objective2" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yakJyqRCEe-hA-m3F63kgQ" name="okrTableInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yakJy6RCEe-hA-m3F63kgQ" type="JAVA_METHOD" expression="setObjective2">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yakJzKRCEe-hA-m3F63kgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yakJzaRCEe-hA-m3F63kgQ" name="okrTable" content="okrTable" type="TYPE_VARIABLE" returnType="com.company.model.OKRTabelle">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yakJzqRCEe-hA-m3F63kgQ" name="okrTable" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKRTabelle"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yakJz6RCEe-hA-m3F63kgQ" name="okrTableInput.zustaendigkeit2" content="okrTableInput?.zustaendigkeit2" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yakJ0KRCEe-hA-m3F63kgQ" name="okrTableInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yakJ0aRCEe-hA-m3F63kgQ" type="JAVA_METHOD" expression="setZustaendigkeit2">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yakJ0qRCEe-hA-m3F63kgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yakJ06RCEe-hA-m3F63kgQ" name="okrTable" content="okrTable" type="TYPE_VARIABLE" returnType="com.company.model.OKRTabelle">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yakJ1KRCEe-hA-m3F63kgQ" name="okrTable" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKRTabelle"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yakJ1aRCEe-hA-m3F63kgQ" name="okrTableInput.objective3" content="okrTableInput?.objective3" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yakJ1qRCEe-hA-m3F63kgQ" name="okrTableInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yakJ16RCEe-hA-m3F63kgQ" type="JAVA_METHOD" expression="setObjective3">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yakJ2KRCEe-hA-m3F63kgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yakJ2aRCEe-hA-m3F63kgQ" name="okrTable" content="okrTable" type="TYPE_VARIABLE" returnType="com.company.model.OKRTabelle">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yakJ2qRCEe-hA-m3F63kgQ" name="okrTable" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKRTabelle"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yakJ26RCEe-hA-m3F63kgQ" name="okrTableInput.zustaendigkeit3" content="okrTableInput?.zustaendigkeit3" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yakJ3KRCEe-hA-m3F63kgQ" name="okrTableInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yakJ3aRCEe-hA-m3F63kgQ" type="JAVA_METHOD" expression="setZustaendigkeit3">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yakJ3qRCEe-hA-m3F63kgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yakJ36RCEe-hA-m3F63kgQ" name="okrTable" content="okrTable" type="TYPE_VARIABLE" returnType="com.company.model.OKRTabelle">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yakJ4KRCEe-hA-m3F63kgQ" name="okrTable" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKRTabelle"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yakJ4aRCEe-hA-m3F63kgQ" name="okrTableInput.keyresult1" content="okrTableInput?.keyresult1" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yakJ4qRCEe-hA-m3F63kgQ" name="okrTableInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yakJ46RCEe-hA-m3F63kgQ" type="JAVA_METHOD" expression="setKeyresult1">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yakJ5KRCEe-hA-m3F63kgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yakJ5aRCEe-hA-m3F63kgQ" name="okrTable" content="okrTable" type="TYPE_VARIABLE" returnType="com.company.model.OKRTabelle">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yakJ5qRCEe-hA-m3F63kgQ" name="okrTable" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKRTabelle"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yakJ56RCEe-hA-m3F63kgQ" name="okrTableInput.keyresult2" content="okrTableInput?.keyresult2" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yakJ6KRCEe-hA-m3F63kgQ" name="okrTableInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yakJ6aRCEe-hA-m3F63kgQ" type="JAVA_METHOD" expression="setKeyresult2">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yakJ6qRCEe-hA-m3F63kgQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yakJ66RCEe-hA-m3F63kgQ" name="okrTable" content="okrTable" type="TYPE_VARIABLE" returnType="com.company.model.OKRTabelle">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yakJ7KRCEe-hA-m3F63kgQ" name="okrTable" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKRTabelle"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yakJ7aRCEe-hA-m3F63kgQ" name="okrTableInput.keyresult3" content="okrTableInput?.keyresult3" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yakJ7qRCEe-hA-m3F63kgQ" name="okrTableInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yakJ76RCEe-hA-m3F63kgQ" type="JAVA_METHOD" expression="setKeyresult3">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_I2vBo6LLEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_I2vBpKLLEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_I2vBpaLLEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_I2vBp6LLEe-YhYlYVX9NAA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_I2vBpqLLEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_I2vBqaLLEe-YhYlYVX9NAA">
            <targetForm xmi:type="expression:Expression" xmi:id="_i_n8IKQ2Ee-e_PUYJW9ZgA" name="OKRZuweisenFormNew" content="12378150-759d-472f-9b0d-cfd5390c6250" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_I2vBqKLLEe-YhYlYVX9NAA">
            <inputs xmi:type="process:ContractInput" xmi:id="_yakJsKRCEe-hA-m3F63kgQ" name="okrTableInput" type="COMPLEX" dataReference="okrTable">
              <inputs xmi:type="process:ContractInput" xmi:id="_yakJsaRCEe-hA-m3F63kgQ" name="objective1"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yakJsqRCEe-hA-m3F63kgQ" name="zustaendigkeit1"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yakJs6RCEe-hA-m3F63kgQ" name="objective2"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yakJtKRCEe-hA-m3F63kgQ" name="zustaendigkeit2"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yakJtaRCEe-hA-m3F63kgQ" name="objective3"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yakJtqRCEe-hA-m3F63kgQ" name="zustaendigkeit3"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yakJt6RCEe-hA-m3F63kgQ" name="keyresult1"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yakJuKRCEe-hA-m3F63kgQ" name="keyresult2"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yakJuaRCEe-hA-m3F63kgQ" name="keyresult3"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_I2vBq6LLEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="__-UaAKLLEe-YhYlYVX9NAA" name="Gateway3" outgoing="__-W2QKLLEe-YhYlYVX9NAA" incoming="_I28dAKLLEe-YhYlYVX9NAA _Fq3QoKLNEe-YhYlYVX9NAA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__-UaAqLLEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__-UaAaLLEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__-UaA6LLEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_pEjXgKLMEe-YhYlYVX9NAA" name="Erinnerung senden" outgoing="_pEnB4KLMEe-YhYlYVX9NAA" incoming="__-W2QKLLEe-YhYlYVX9NAA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pEj-kaLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pEj-kKLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pEj-kqLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pEj-k6LMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pEj-lKLMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pEkloKLMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pEkloqLMEe-YhYlYVX9NAA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pEkloaLMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pEklpKLMEe-YhYlYVX9NAA">
            <targetForm xmi:type="expression:Expression" xmi:id="_HobTwKQxEe-e_PUYJW9ZgA" name="newForm9" content="f0a0075a-de44-47d1-839d-3f51fa320c73" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pEklo6LMEe-YhYlYVX9NAA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_pEklpqLMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_rqjwcKLMEe-YhYlYVX9NAA" name="Gateway4" outgoing="_rqmMsKLMEe-YhYlYVX9NAA _7AQIEKLMEe-YhYlYVX9NAA" incoming="_pEnB4KLMEe-YhYlYVX9NAA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rqkXgaLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rqkXgKLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rqkXgqLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_-CuakKLMEe-YhYlYVX9NAA" name="Check-In (2)" outgoing="_-Cw20KLMEe-YhYlYVX9NAA" incoming="_rqmMsKLMEe-YhYlYVX9NAA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-CvBoaLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-CvBoKLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-CvBoqLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-CvBo6LMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-CvBpKLMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-CvBpaLMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-CvBp6LMEe-YhYlYVX9NAA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-CvBpqLMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_-CvBqaLMEe-YhYlYVX9NAA">
            <targetForm xmi:type="expression:Expression" xmi:id="_8K_3EKREEe-hA-m3F63kgQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_-CvBqKLMEe-YhYlYVX9NAA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_-CvBq6LMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="__v4f8KLMEe-YhYlYVX9NAA" name="Gateway5" outgoing="__v68MKLMEe-YhYlYVX9NAA" incoming="_-Cw20KLMEe-YhYlYVX9NAA _AGzyMKLNEe-YhYlYVX9NAA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__v5HAaLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__v5HAKLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__v5HAqLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_CUP6IKLNEe-YhYlYVX9NAA" name="Weitere Check-Ins für Cycle geplant?" outgoing="_CUSWYKLNEe-YhYlYVX9NAA _Fq3QoKLNEe-YhYlYVX9NAA" incoming="__v68MKLMEe-YhYlYVX9NAA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CUP6IqLNEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CUP6IaLNEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_CUP6I6LNEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_rCMVoKLcEe-XR5i3qur68g" name="Cluster definieren OKR-Facilitator" outgoing="_CY3dsKN4Ee-prI0FBJ3d6g" incoming="_sAX1IKLcEe-XR5i3qur68g" outputData="_rCMVpKLcEe-XR5i3qur68g" storeOutput="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rCMVoaLcEe-XR5i3qur68g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rCMVoqLcEe-XR5i3qur68g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rCMVo6LcEe-XR5i3qur68g" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:JavaObjectData" xmi:id="_rCMVpKLcEe-XR5i3qur68g" name="instanceClusterResult" dataType="_wa74sqEGEe-aYLU-FfmCmw" className="java.util.List">
            <defaultValue xmi:type="expression:Expression" xmi:id="_rCMVpaLcEe-XR5i3qur68g" content="" returnType="java.util.List"/>
          </data>
          <operations xmi:type="expression:Operation" xmi:id="_cjLD5qN3Ee-prI0FBJ3d6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_cjLD56N3Ee-prI0FBJ3d6g" name="cluster" content="cluster" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_k-2OQKP8Ee-e_PUYJW9ZgA" name="cluster" multiple="true" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.Cluster"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_cjLD6aN3Ee-prI0FBJ3d6g" name="clusterInput" content="def clusterList = []&#xD;&#xA;//For each item collected in multiple input&#xD;&#xA;clusterInput.each{&#xD;&#xA;&#x9;//Add a new composed Cluster instance&#xD;&#xA;&#x9;clusterList.add({ currentClusterInput ->&#xD;&#xA;&#x9;&#x9;def clusterVar = new com.company.model.Cluster()&#xD;&#xA;&#x9;&#x9;clusterVar.clusterContent = currentClusterInput.clusterContent&#xD;&#xA;&#x9;&#x9;clusterVar.clusterTitle = currentClusterInput.clusterTitle&#xD;&#xA;&#x9;&#x9;return clusterVar&#xD;&#xA;&#x9;}(it))&#xD;&#xA;}&#xD;&#xA;return clusterList" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Collection">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_SiDGUKP9Ee-e_PUYJW9ZgA" name="clusterInput" type="COMPLEX" multiple="true" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_cjLD7KN3Ee-prI0FBJ3d6g" type="JAVA_METHOD" expression="addAll">
              <inputTypes>java.util.Collection</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_ea8d0qN3Ee-prI0FBJ3d6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ea8d06N3Ee-prI0FBJ3d6g" name="clustersCompleted" content="clustersCompleted" type="TYPE_VARIABLE" returnType="com.company.model.ClustersCompleted">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ea8d1KN3Ee-prI0FBJ3d6g" name="clustersCompleted" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.ClustersCompleted"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ea8d1aN3Ee-prI0FBJ3d6g" name="clustersCompletedInput.completed" content="clustersCompletedInput?.completed" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ea8d1qN3Ee-prI0FBJ3d6g" name="clustersCompletedInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_ea8d16N3Ee-prI0FBJ3d6g" type="JAVA_METHOD" expression="setCompleted">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rCMVs6LcEe-XR5i3qur68g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rCMVtKLcEe-XR5i3qur68g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rCMVtaLcEe-XR5i3qur68g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rCMVtqLcEe-XR5i3qur68g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="com.company.model.Cluster" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rCMVt6LcEe-XR5i3qur68g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_rCMVuKLcEe-XR5i3qur68g">
            <targetForm xmi:type="expression:Expression" xmi:id="_rCMVuaLcEe-XR5i3qur68g" name="clusteringFacilitatorForm" content="984cc5a3-96a6-492d-ae79-7d76b1e07403" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_rCMVuqLcEe-XR5i3qur68g">
            <inputs xmi:type="process:ContractInput" xmi:id="_cjLD4KN3Ee-prI0FBJ3d6g" name="clusterInput" type="COMPLEX" multiple="true" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_cjLD4aN3Ee-prI0FBJ3d6g" name="persistenceId_string" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_cjLD4qN3Ee-prI0FBJ3d6g" name="clusterContent" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_cjLD46N3Ee-prI0FBJ3d6g" name="clusterTitle" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_ea72wKN3Ee-prI0FBJ3d6g" name="clustersCompletedInput" type="COMPLEX" dataReference="clustersCompleted" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_ea8d0KN3Ee-prI0FBJ3d6g" name="completed" type="BOOLEAN" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_ea8d0aN3Ee-prI0FBJ3d6g" expression="clustersCompletedInput?.completed != null" errorMessage="completed is mandatory for ClustersCompleted" name="mandatory_clustersCompletedInput_completed">
              <inputNames>clustersCompletedInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_rCMVxaLcEe-XR5i3qur68g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Mcfh8KELEe-aYLU-FfmCmw" name="Einladung akzeptieren" outgoing="_lwiT4KOOEe-prI0FBJ3d6g" incoming="_N6sjYKLOEe-YhYlYVX9NAA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_y0dCsqEIEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_y0dCsaEIEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_y0dCs6EIEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_-MDlcaK7Ee-pXblqnP0p3A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_-MDlcqK7Ee-pXblqnP0p3A" name="einladung" content="einladung" type="TYPE_VARIABLE" returnType="com.company.model.Einladung">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_-MDlc6K7Ee-pXblqnP0p3A" name="einladung" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.Einladung"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_-MDldKK7Ee-pXblqnP0p3A" name="einladungInput.datum" content="einladungInput?.datum" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDateTime">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_-MDldaK7Ee-pXblqnP0p3A" name="einladungInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_-MDldqK7Ee-pXblqnP0p3A" type="JAVA_METHOD" expression="setDatum">
              <inputTypes>java.time.LocalDateTime</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_y0dCtKEIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_y0dCtaEIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_y0dCtqEIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_y0dCuKEIEe-aYLU-FfmCmw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_y0dCt6EIEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Mcfh-qELEe-aYLU-FfmCmw">
            <targetForm xmi:type="expression:Expression" xmi:id="_EICbsKK8Ee-pXblqnP0p3A" name="einladungAkzeptierenForm" content="6addbe5c-d876-417d-975f-032e758300c0" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Mcfh-aELEe-aYLU-FfmCmw">
            <inputs xmi:type="process:ContractInput" xmi:id="_-MC-YKK7Ee-pXblqnP0p3A" name="einladungInput" type="COMPLEX" dataReference="einladung" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_-MC-YaK7Ee-pXblqnP0p3A" name="datum" type="LOCALDATETIME" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_-MDlcKK7Ee-pXblqnP0p3A" expression="einladungInput?.datum != null" errorMessage="datum is mandatory for Einladung" name="mandatory_einladungInput_datum">
              <inputNames>einladungInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Mcfh_KELEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_I3R5UKEMEe-aYLU-FfmCmw" name="Cluster definieren Team-Member" outgoing="_sAX1IKLcEe-XR5i3qur68g" incoming="_ALaVYKN9Ee-prI0FBJ3d6g" outputData="_frEvQKHSEe-aYLU-FfmCmw" storeOutput="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ld9dIaELEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ld9dIKELEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ld9dIqELEe-aYLU-FfmCmw" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:JavaObjectData" xmi:id="_frEvQKHSEe-aYLU-FfmCmw" name="instanceClusterResult" dataType="_wa74sqEGEe-aYLU-FfmCmw" className="java.util.List">
            <defaultValue xmi:type="expression:Expression" xmi:id="_frEvQaHSEe-aYLU-FfmCmw" content="" returnType="java.util.List"/>
          </data>
          <operations xmi:type="expression:Operation" xmi:id="_JJUTRqN3Ee-prI0FBJ3d6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_JJUTR6N3Ee-prI0FBJ3d6g" name="cluster" content="cluster" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_j71SEKP8Ee-e_PUYJW9ZgA" name="cluster" multiple="true" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.Cluster"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_JJUTSaN3Ee-prI0FBJ3d6g" name="clusterInput" content="def clusterList = []&#xD;&#xA;//For each item collected in multiple input&#xD;&#xA;clusterInput.each{&#xD;&#xA;&#x9;//Add a new composed Cluster instance&#xD;&#xA;&#x9;clusterList.add({ currentClusterInput ->&#xD;&#xA;&#x9;&#x9;def clusterVar = new com.company.model.Cluster()&#xD;&#xA;&#x9;&#x9;clusterVar.clusterContent = currentClusterInput.clusterContent&#xD;&#xA;&#x9;&#x9;clusterVar.clusterTitle = currentClusterInput.clusterTitle&#xD;&#xA;&#x9;&#x9;return clusterVar&#xD;&#xA;&#x9;}(it))&#xD;&#xA;}&#xD;&#xA;return clusterList" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Collection">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ZCVIcKN5Ee-prI0FBJ3d6g" name="clusterInput" type="COMPLEX" multiple="true"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_JJUTS6N3Ee-prI0FBJ3d6g" type="JAVA_METHOD" expression="addAll">
              <inputTypes>java.util.Collection</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_MQb1M6N3Ee-prI0FBJ3d6g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_MQb1NKN3Ee-prI0FBJ3d6g" name="clustersCompleted" content="clustersCompleted" type="TYPE_VARIABLE" returnType="com.company.model.ClustersCompleted">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_MQb1NaN3Ee-prI0FBJ3d6g" name="clustersCompleted" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.ClustersCompleted"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_MQb1NqN3Ee-prI0FBJ3d6g" name="clustersCompletedInput.completed" content="clustersCompletedInput?.completed" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_MQb1N6N3Ee-prI0FBJ3d6g" name="clustersCompletedInput" type="COMPLEX"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_MQb1OKN3Ee-prI0FBJ3d6g" type="JAVA_METHOD" expression="setCompleted">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Ld9dI6ELEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Ld9dJKELEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Ld9dJaELEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Ld9dJ6ELEe-aYLU-FfmCmw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="com.company.model.Cluster" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Ld9dJqELEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_I3SgaaEMEe-aYLU-FfmCmw">
            <targetForm xmi:type="expression:Expression" xmi:id="_NkznIKN3Ee-prI0FBJ3d6g" name="clusteringTeammemberForm" content="5c4029d9-214d-489e-b599-33b78a874d88" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_I3SgaKEMEe-aYLU-FfmCmw">
            <inputs xmi:type="process:ContractInput" xmi:id="_JJUTQKN3Ee-prI0FBJ3d6g" name="clusterInput" type="COMPLEX" multiple="true">
              <inputs xmi:type="process:ContractInput" xmi:id="_JJUTQaN3Ee-prI0FBJ3d6g" name="persistenceId_string"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JJUTQqN3Ee-prI0FBJ3d6g" name="clusterContent"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_JJUTQ6N3Ee-prI0FBJ3d6g" name="clusterTitle"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_MQb1MKN3Ee-prI0FBJ3d6g" name="clustersCompletedInput" type="COMPLEX" dataReference="clustersCompleted">
              <inputs xmi:type="process:ContractInput" xmi:id="_MQb1MaN3Ee-prI0FBJ3d6g" name="completed" type="BOOLEAN"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_MQb1MqN3Ee-prI0FBJ3d6g" expression="clustersCompletedInput?.completed != null" errorMessage="completed is mandatory for ClustersCompleted" name="mandatory_clustersCompletedInput_completed">
              <inputNames>clustersCompletedInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_I3Sga6EMEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_-AYoQKN8Ee-prI0FBJ3d6g" name="vollständig?" outgoing="_AzuSkKN9Ee-prI0FBJ3d6g _b0u8YKQuEe-e_PUYJW9ZgA" incoming="_CY3dsKN4Ee-prI0FBJ3d6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-AYoQqN8Ee-prI0FBJ3d6g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-AYoQaN8Ee-prI0FBJ3d6g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-AYoQ6N8Ee-prI0FBJ3d6g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ALWrAKN9Ee-prI0FBJ3d6g" name="Gateway6" outgoing="_ALaVYKN9Ee-prI0FBJ3d6g" incoming="_AzuSkKN9Ee-prI0FBJ3d6g _lwiT4KOOEe-prI0FBJ3d6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ALXSEaN9Ee-prI0FBJ3d6g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ALXSEKN9Ee-prI0FBJ3d6g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ALXSEqN9Ee-prI0FBJ3d6g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_eTS-4KOREe-prI0FBJ3d6g" name="IOO-Tabellen erstellen" outgoing="_DIaM0KOPEe-prI0FBJ3d6g" incoming="_g-MwkKQuEe-e_PUYJW9ZgA" collectionDataToMultiInstantiate="_1MfMcKP6Ee-XMtg22bHIlQ" listDataContainingOutputResults="_rl8EMKOSEe-prI0FBJ3d6g" storeOutput="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oCK_UqOOEe-prI0FBJ3d6g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oCK_UaOOEe-prI0FBJ3d6g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oCK_U6OOEe-prI0FBJ3d6g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_AWSyqqQgEe-e_PUYJW9ZgA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_AWSyq6QgEe-e_PUYJW9ZgA" name="okr" content="okr" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Du2lsKQnEe-e_PUYJW9ZgA" name="okr" multiple="true" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKR"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_AWSyraQgEe-e_PUYJW9ZgA" name="okrInput" content="&#xD;&#xA;def oKRVar = new com.company.model.OKR()&#xD;&#xA;oKRVar.inputString = okrInput.inputString&#xD;&#xA;oKRVar.outputString = okrInput.outputString&#xD;&#xA;oKRVar.outcomeString = okrInput.outcomeString&#xD;&#xA;&#xD;&#xA;return oKRVar&#xD;&#xA;&#x9;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_bVlooKQ2Ee-e_PUYJW9ZgA" name="okrInput" type="COMPLEX" multiple="true" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_AWSyr6QgEe-e_PUYJW9ZgA" type="JAVA_METHOD" expression="add">
              <inputTypes>java.lang.Object</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_oCK_VKOOEe-prI0FBJ3d6g" name="loopWhile()" content="return (okr.size() &lt; cluster.size());" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qB5lgKQJEe-e_PUYJW9ZgA" name="cluster" multiple="true" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.Cluster"/>
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_qB5lgaQJEe-e_PUYJW9ZgA" name="okr" multiple="true" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKR"/>
          </loopCondition>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_oCK_VaOOEe-prI0FBJ3d6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_oCK_VqOOEe-prI0FBJ3d6g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_oCK_WKOOEe-prI0FBJ3d6g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="com.company.model.Cluster" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_oCK_V6OOEe-prI0FBJ3d6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_eTTl-aOREe-prI0FBJ3d6g">
            <targetForm xmi:type="expression:Expression" xmi:id="_tQ4uYKQnEe-e_PUYJW9ZgA" name="IOOtabelleErstellenForm" content="f55818e9-e201-4a11-a4ed-d30f6392a29c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_eTTl-KOREe-prI0FBJ3d6g">
            <inputs xmi:type="process:ContractInput" xmi:id="_eP6mYKQjEe-e_PUYJW9ZgA" name="okrInput" type="COMPLEX" multiple="true" dataReference="okr" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_eP6mYaQjEe-e_PUYJW9ZgA" name="persistenceId_string" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_eP6mYqQjEe-e_PUYJW9ZgA" name="inputString" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_eP6mY6QjEe-e_PUYJW9ZgA" name="outputString" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_eP6mZKQjEe-e_PUYJW9ZgA" name="outcomeString" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_eTTl-6OREe-prI0FBJ3d6g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_kmqlsKQmEe-e_PUYJW9ZgA" name="Gateway 77" outgoing="_g-MwkKQuEe-e_PUYJW9ZgA" incoming="_tJ9ccKQmEe-e_PUYJW9ZgA _b0u8YKQuEe-e_PUYJW9ZgA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kmu3IaQmEe-e_PUYJW9ZgA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kmu3IKQmEe-e_PUYJW9ZgA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kmu3IqQmEe-e_PUYJW9ZgA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_q9sZMKQmEe-e_PUYJW9ZgA" name="fertig?" outgoing="_q9u1cKQmEe-e_PUYJW9ZgA _tJ9ccKQmEe-e_PUYJW9ZgA" incoming="_DIaM0KOPEe-prI0FBJ3d6g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_q9sZMqQmEe-e_PUYJW9ZgA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_q9sZMaQmEe-e_PUYJW9ZgA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_q9sZM6QmEe-e_PUYJW9ZgA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_qVBpIKRGEe-hA-m3F63kgQ" name="Gateway7" outgoing="_vQ_z4KRGEe-hA-m3F63kgQ _0kZnMKRGEe-hA-m3F63kgQ" incoming="_CUSWYKLNEe-YhYlYVX9NAA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qVCQMaRGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qVCQMKRGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qVCQMqRGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_xc2ncKRGEe-hA-m3F63kgQ" name="Retrospective/Reporting durchführen Facilitator" outgoing="_31HKAKRGEe-hA-m3F63kgQ" incoming="_0kZnMKRGEe-hA-m3F63kgQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xc2ncqRGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xc2ncaRGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xc2nc6RGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xc2ndKRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xc2ndaRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xc2ndqRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xc2neKRGEe-hA-m3F63kgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xc2nd6RGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_xc2neqRGEe-hA-m3F63kgQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_xc2ne6RGEe-hA-m3F63kgQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_xc2neaRGEe-hA-m3F63kgQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_xc2nfKRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_31F74KRGEe-hA-m3F63kgQ" name="Gateway8" outgoing="_4w-VUaRGEe-hA-m3F63kgQ" incoming="_31HKAKRGEe-hA-m3F63kgQ _4OnPIKRGEe-hA-m3F63kgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_31F74qRGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_31F74aRGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_31F746RGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_4w9uQKRGEe-hA-m3F63kgQ" name="Dokumentation schreiben" outgoing="_60LjMKRGEe-hA-m3F63kgQ" incoming="_4w-VUaRGEe-hA-m3F63kgQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4w9uQqRGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4w9uQaRGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4w9uQ6RGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_4w9uRKRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_4w9uRaRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4w9uRqRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_4w9uSKRGEe-hA-m3F63kgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_4w9uR6RGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_m1xfoKEHEe-aYLU-FfmCmw" name="Team-Member" actor="_Ea7-8KEOEe-aYLU-FfmCmw">
        <elements xmi:type="process:Task" xmi:id="_tiaC4KLMEe-YhYlYVX9NAA" name="Check-In" outgoing="_AGzyMKLNEe-YhYlYVX9NAA" incoming="_7AQIEKLMEe-YhYlYVX9NAA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tiap8KLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tiaC4aLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tiap8aLMEe-YhYlYVX9NAA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tiap8qLMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tiap86LMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tiap9KLMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tiap9qLMEe-YhYlYVX9NAA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tiap9aLMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_tiap-KLMEe-YhYlYVX9NAA">
            <targetForm xmi:type="expression:Expression" xmi:id="_8K_3EaREEe-hA-m3F63kgQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_tiap96LMEe-YhYlYVX9NAA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_tiap-qLMEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_rnMboKRGEe-hA-m3F63kgQ" name="Retrospective/Reporting durchführen Teammember" outgoing="_4OnPIKRGEe-hA-m3F63kgQ" incoming="_vQ_z4KRGEe-hA-m3F63kgQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rnMboqRGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rnMboaRGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rnMbo6RGEe-hA-m3F63kgQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rnMbpKRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rnMbpaRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rnMbpqRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rnMbqKRGEe-hA-m3F63kgQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rnMbp6RGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_rnMbqqRGEe-hA-m3F63kgQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_rnMbq6RGEe-hA-m3F63kgQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_rnMbqaRGEe-hA-m3F63kgQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_rnMbrKRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_ThiTIKHpEe-aYLU-FfmCmw" name="einladung" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.Einladung">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ThiTIaHpEe-aYLU-FfmCmw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_DaRFwKN3Ee-prI0FBJ3d6g" name="clustersCompleted" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.ClustersCompleted">
        <defaultValue xmi:type="expression:Expression" xmi:id="_DaRFwaN3Ee-prI0FBJ3d6g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_rl8EMKOSEe-prI0FBJ3d6g" name="okr" multiple="true" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKR">
        <defaultValue xmi:type="expression:Expression" xmi:id="_rl8EMaOSEe-prI0FBJ3d6g" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_1MfMcKP6Ee-XMtg22bHIlQ" name="cluster" multiple="true" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.Cluster">
        <defaultValue xmi:type="expression:Expression" xmi:id="_1MfMcaP6Ee-XMtg22bHIlQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_5igJoKQqEe-e_PUYJW9ZgA" name="currentCluster" dataType="_wa74sqEGEe-aYLU-FfmCmw" className="com.company.model.Cluster">
        <defaultValue xmi:type="expression:Expression" xmi:id="_5igJoaQqEe-e_PUYJW9ZgA" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Cluster"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_GqDuYKQuEe-e_PUYJW9ZgA" name="clusterCounter" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.ClusterCounter">
        <defaultValue xmi:type="expression:Expression" xmi:id="_GqDuYaQuEe-e_PUYJW9ZgA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Md4NgKQ2Ee-e_PUYJW9ZgA" name="okrTable" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKRTabelle">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Md4NgaQ2Ee-e_PUYJW9ZgA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_g99-z6EHEe-aYLU-FfmCmw">
        <targetForm xmi:type="expression:Expression" xmi:id="_swHEQKLBEe-pXblqnP0p3A" name="startProcessForm" content="7ac551cd-acaa-4701-ab50-9a58b7d13191" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_g99-0aEHEe-aYLU-FfmCmw">
        <targetForm xmi:type="expression:Expression" xmi:id="_yjOAcKLDEe-pXblqnP0p3A" name="overviewForm" content="5c3ce8e2-7a4c-4867-8bac-78cf99e7c5ef" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g5B2gKHaEe-aYLU-FfmCmw" target="_u2bt8KEIEe-aYLU-FfmCmw" source="_goVIEKHaEe-aYLU-FfmCmw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g5CdkKHaEe-aYLU-FfmCmw"/>
        <condition xmi:type="expression:Expression" xmi:id="_g5CdkaHaEe-aYLU-FfmCmw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zzxiAKLGEe-pXblqnP0p3A" target="_vrGFEKEIEe-aYLU-FfmCmw" source="_u2bt8KEIEe-aYLU-FfmCmw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zzxiAaLGEe-pXblqnP0p3A"/>
        <condition xmi:type="expression:Expression" xmi:id="_zzxiAqLGEe-pXblqnP0p3A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_I28dAKLLEe-YhYlYVX9NAA" target="__-UaAKLLEe-YhYlYVX9NAA" source="_I2qwMKLLEe-YhYlYVX9NAA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_I28dAaLLEe-YhYlYVX9NAA"/>
        <condition xmi:type="expression:Expression" xmi:id="_I28dAqLLEe-YhYlYVX9NAA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__-W2QKLLEe-YhYlYVX9NAA" target="_pEjXgKLMEe-YhYlYVX9NAA" source="__-UaAKLLEe-YhYlYVX9NAA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__-W2QaLLEe-YhYlYVX9NAA"/>
        <condition xmi:type="expression:Expression" xmi:id="__-W2QqLLEe-YhYlYVX9NAA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pEnB4KLMEe-YhYlYVX9NAA" target="_rqjwcKLMEe-YhYlYVX9NAA" source="_pEjXgKLMEe-YhYlYVX9NAA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pEnB4aLMEe-YhYlYVX9NAA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pEnB4qLMEe-YhYlYVX9NAA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rqmMsKLMEe-YhYlYVX9NAA" target="_-CuakKLMEe-YhYlYVX9NAA" source="_rqjwcKLMEe-YhYlYVX9NAA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rqmMsaLMEe-YhYlYVX9NAA"/>
        <condition xmi:type="expression:Expression" xmi:id="_rqmMsqLMEe-YhYlYVX9NAA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7AQIEKLMEe-YhYlYVX9NAA" target="_tiaC4KLMEe-YhYlYVX9NAA" source="_rqjwcKLMEe-YhYlYVX9NAA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7AQIEaLMEe-YhYlYVX9NAA"/>
        <condition xmi:type="expression:Expression" xmi:id="_7AQIEqLMEe-YhYlYVX9NAA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-Cw20KLMEe-YhYlYVX9NAA" target="__v4f8KLMEe-YhYlYVX9NAA" source="_-CuakKLMEe-YhYlYVX9NAA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-Cw20aLMEe-YhYlYVX9NAA"/>
        <condition xmi:type="expression:Expression" xmi:id="_-Cw20qLMEe-YhYlYVX9NAA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__v68MKLMEe-YhYlYVX9NAA" target="_CUP6IKLNEe-YhYlYVX9NAA" source="__v4f8KLMEe-YhYlYVX9NAA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__v68MaLMEe-YhYlYVX9NAA"/>
        <condition xmi:type="expression:Expression" xmi:id="__v68MqLMEe-YhYlYVX9NAA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AGzyMKLNEe-YhYlYVX9NAA" target="__v4f8KLMEe-YhYlYVX9NAA" source="_tiaC4KLMEe-YhYlYVX9NAA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AGzyMaLNEe-YhYlYVX9NAA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AGzyMqLNEe-YhYlYVX9NAA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CUSWYKLNEe-YhYlYVX9NAA" name="nein" target="_qVBpIKRGEe-hA-m3F63kgQ" source="_CUP6IKLNEe-YhYlYVX9NAA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CUSWYaLNEe-YhYlYVX9NAA"/>
        <condition xmi:type="expression:Expression" xmi:id="_CUSWYqLNEe-YhYlYVX9NAA" name="checkNoMoreCheckIns()" content="if (Prozess.prozessStatus){&#xD;&#xA;&#x9;return true&#xD;&#xA;}" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Fq3QoKLNEe-YhYlYVX9NAA" name="ja" target="__-UaAKLLEe-YhYlYVX9NAA" source="_CUP6IKLNEe-YhYlYVX9NAA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Fq3QoaLNEe-YhYlYVX9NAA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Fq3QoqLNEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_N6sjYKLOEe-YhYlYVX9NAA" target="_Mcfh8KELEe-aYLU-FfmCmw" source="_vrGFEKEIEe-aYLU-FfmCmw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_N6sjYaLOEe-YhYlYVX9NAA"/>
        <condition xmi:type="expression:Expression" xmi:id="_N6sjYqLOEe-YhYlYVX9NAA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sAX1IKLcEe-XR5i3qur68g" target="_rCMVoKLcEe-XR5i3qur68g" source="_I3R5UKEMEe-aYLU-FfmCmw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sAcGkKLcEe-XR5i3qur68g"/>
        <condition xmi:type="expression:Expression" xmi:id="_sAcGkaLcEe-XR5i3qur68g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CY3dsKN4Ee-prI0FBJ3d6g" target="_-AYoQKN8Ee-prI0FBJ3d6g" source="_rCMVoKLcEe-XR5i3qur68g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CY3dsaN4Ee-prI0FBJ3d6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_CY3dsqN4Ee-prI0FBJ3d6g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ALaVYKN9Ee-prI0FBJ3d6g" target="_I3R5UKEMEe-aYLU-FfmCmw" source="_ALWrAKN9Ee-prI0FBJ3d6g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ALaVYaN9Ee-prI0FBJ3d6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_ALaVYqN9Ee-prI0FBJ3d6g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AzuSkKN9Ee-prI0FBJ3d6g" name="nein" target="_ALWrAKN9Ee-prI0FBJ3d6g" source="_-AYoQKN8Ee-prI0FBJ3d6g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AzuSkaN9Ee-prI0FBJ3d6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_AzuSkqN9Ee-prI0FBJ3d6g" name="newScript()" content="return clustersCompleted.completed == false;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_JHopgKN9Ee-prI0FBJ3d6g" name="clustersCompleted" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.ClustersCompleted"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lwiT4KOOEe-prI0FBJ3d6g" target="_ALWrAKN9Ee-prI0FBJ3d6g" source="_Mcfh8KELEe-aYLU-FfmCmw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lwiT4aOOEe-prI0FBJ3d6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_lwiT4qOOEe-prI0FBJ3d6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DIaM0KOPEe-prI0FBJ3d6g" target="_q9sZMKQmEe-e_PUYJW9ZgA" source="_eTS-4KOREe-prI0FBJ3d6g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DIaM0aOPEe-prI0FBJ3d6g"/>
        <condition xmi:type="expression:Expression" xmi:id="_DIaM0qOPEe-prI0FBJ3d6g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_q9u1cKQmEe-e_PUYJW9ZgA" name="ja" target="_I2qwMKLLEe-YhYlYVX9NAA" source="_q9sZMKQmEe-e_PUYJW9ZgA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_q9u1caQmEe-e_PUYJW9ZgA"/>
        <condition xmi:type="expression:Expression" xmi:id="_q9u1cqQmEe-e_PUYJW9ZgA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tJ9ccKQmEe-e_PUYJW9ZgA" name="nein" target="_kmqlsKQmEe-e_PUYJW9ZgA" source="_q9sZMKQmEe-e_PUYJW9ZgA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tJ9ccaQmEe-e_PUYJW9ZgA"/>
        <condition xmi:type="expression:Expression" xmi:id="_tJ9ccqQmEe-e_PUYJW9ZgA" name="newScript()" content="return okr.size() &lt; cluster.size()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nDqWIKQyEe-e_PUYJW9ZgA" name="cluster" multiple="true" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.Cluster"/>
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nDqWIaQyEe-e_PUYJW9ZgA" name="okr" multiple="true" dataType="_wa74tKEGEe-aYLU-FfmCmw" className="com.company.model.OKR"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_b0u8YKQuEe-e_PUYJW9ZgA" name="ja" target="_kmqlsKQmEe-e_PUYJW9ZgA" source="_-AYoQKN8Ee-prI0FBJ3d6g" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_b0u8YaQuEe-e_PUYJW9ZgA"/>
        <condition xmi:type="expression:Expression" xmi:id="_b0u8YqQuEe-e_PUYJW9ZgA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g-MwkKQuEe-e_PUYJW9ZgA" target="_eTS-4KOREe-prI0FBJ3d6g" source="_kmqlsKQmEe-e_PUYJW9ZgA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g-MwkaQuEe-e_PUYJW9ZgA"/>
        <condition xmi:type="expression:Expression" xmi:id="_g-MwkqQuEe-e_PUYJW9ZgA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vQ_z4KRGEe-hA-m3F63kgQ" target="_rnMboKRGEe-hA-m3F63kgQ" source="_qVBpIKRGEe-hA-m3F63kgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vQ_z4aRGEe-hA-m3F63kgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_vQ_z4qRGEe-hA-m3F63kgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0kZnMKRGEe-hA-m3F63kgQ" target="_xc2ncKRGEe-hA-m3F63kgQ" source="_qVBpIKRGEe-hA-m3F63kgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0kZnMaRGEe-hA-m3F63kgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0kZnMqRGEe-hA-m3F63kgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_31HKAKRGEe-hA-m3F63kgQ" target="_31F74KRGEe-hA-m3F63kgQ" source="_xc2ncKRGEe-hA-m3F63kgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_31HKAaRGEe-hA-m3F63kgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_31HKAqRGEe-hA-m3F63kgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4OnPIKRGEe-hA-m3F63kgQ" target="_31F74KRGEe-hA-m3F63kgQ" source="_rnMboKRGEe-hA-m3F63kgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4OnPIaRGEe-hA-m3F63kgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_4OnPIqRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4w-VUaRGEe-hA-m3F63kgQ" target="_4w9uQKRGEe-hA-m3F63kgQ" source="_31F74KRGEe-hA-m3F63kgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4w-VUqRGEe-hA-m3F63kgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_4w-VU6RGEe-hA-m3F63kgQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_60LjMKRGEe-hA-m3F63kgQ" target="_CC-WAKKjEe-pXblqnP0p3A" source="_4w9uQKRGEe-hA-m3F63kgQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_60MKQKRGEe-hA-m3F63kgQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_60MKQaRGEe-hA-m3F63kgQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_AgRgMKEOEe-aYLU-FfmCmw" name="OKR-Facilitator" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_Ea7-8KEOEe-aYLU-FfmCmw" name="Team-Member"/>
      <contract xmi:type="process:Contract" xmi:id="_g99-06EHEe-aYLU-FfmCmw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g99-wKEHEe-aYLU-FfmCmw">
        <name xmi:type="expression:Expression" xmi:id="_g99-waEHEe-aYLU-FfmCmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g99-wqEHEe-aYLU-FfmCmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g99-w6EHEe-aYLU-FfmCmw">
        <name xmi:type="expression:Expression" xmi:id="_g99-xKEHEe-aYLU-FfmCmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g99-xaEHEe-aYLU-FfmCmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g99-xqEHEe-aYLU-FfmCmw">
        <name xmi:type="expression:Expression" xmi:id="_g99-x6EHEe-aYLU-FfmCmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g99-yKEHEe-aYLU-FfmCmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g99-yaEHEe-aYLU-FfmCmw">
        <name xmi:type="expression:Expression" xmi:id="_g99-yqEHEe-aYLU-FfmCmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g99-y6EHEe-aYLU-FfmCmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_g99-zKEHEe-aYLU-FfmCmw">
        <name xmi:type="expression:Expression" xmi:id="_g99-zaEHEe-aYLU-FfmCmw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_g99-zqEHEe-aYLU-FfmCmw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_wa74rKEGEe-aYLU-FfmCmw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_wa74raEGEe-aYLU-FfmCmw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_wa74rqEGEe-aYLU-FfmCmw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_wa74r6EGEe-aYLU-FfmCmw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_wa74sKEGEe-aYLU-FfmCmw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_wa74saEGEe-aYLU-FfmCmw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_wa74sqEGEe-aYLU-FfmCmw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_wa74s6EGEe-aYLU-FfmCmw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_wa74tKEGEe-aYLU-FfmCmw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_wa74taEGEe-aYLU-FfmCmw" type="Process" element="_wa74gKEGEe-aYLU-FfmCmw" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_g9_M4KEHEe-aYLU-FfmCmw" type="2007" element="_g90NwKEHEe-aYLU-FfmCmw">
      <children xmi:type="notation:DecorationNode" xmi:id="_g9_z8KEHEe-aYLU-FfmCmw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_g9_z8aEHEe-aYLU-FfmCmw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_iaYSYKEHEe-aYLU-FfmCmw" type="3007" element="_iaXEQKEHEe-aYLU-FfmCmw">
          <children xmi:type="notation:DecorationNode" xmi:id="_iaY5cKEHEe-aYLU-FfmCmw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_iaY5caEHEe-aYLU-FfmCmw" type="7002"/>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_iaYSYaEHEe-aYLU-FfmCmw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_iaYSYqEHEe-aYLU-FfmCmw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_iaYSY6EHEe-aYLU-FfmCmw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_iaY5cqEHEe-aYLU-FfmCmw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iaYSZKEHEe-aYLU-FfmCmw" x="48" y="10" width="1297" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_lStKYKEHEe-aYLU-FfmCmw" type="3007" element="_lSr8QKEHEe-aYLU-FfmCmw">
          <children xmi:type="notation:DecorationNode" xmi:id="_lStxcKEHEe-aYLU-FfmCmw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_lStxcaEHEe-aYLU-FfmCmw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_u2cVA6EIEe-aYLU-FfmCmw" type="3005" element="_u2bt8KEIEe-aYLU-FfmCmw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_u2cVBaEIEe-aYLU-FfmCmw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_u2cVBKEIEe-aYLU-FfmCmw" x="137" y="100" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vrGsLKEIEe-aYLU-FfmCmw" type="3005" element="_vrGFEKEIEe-aYLU-FfmCmw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vrGsLqEIEe-aYLU-FfmCmw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vrGsLaEIEe-aYLU-FfmCmw" x="118" y="250" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_goWWMKHaEe-aYLU-FfmCmw" type="3002" element="_goVIEKHaEe-aYLU-FfmCmw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_goWWMqHaEe-aYLU-FfmCmw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_goWWM6HaEe-aYLU-FfmCmw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_goWWMaHaEe-aYLU-FfmCmw" x="61" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_CDky8KKjEe-pXblqnP0p3A" type="3003" element="_CC-WAKKjEe-pXblqnP0p3A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_CDky8qKjEe-pXblqnP0p3A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_CDky86KjEe-pXblqnP0p3A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CDky8aKjEe-pXblqnP0p3A" x="2246" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_I2zTEKLLEe-YhYlYVX9NAA" type="3005" element="_I2qwMKLLEe-YhYlYVX9NAA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_I2zTEqLLEe-YhYlYVX9NAA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_I2zTEaLLEe-YhYlYVX9NAA" x="1059" y="121"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__-VBEKLLEe-YhYlYVX9NAA" type="3008" element="__-UaAKLLEe-YhYlYVX9NAA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="__-VBEqLLEe-YhYlYVX9NAA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="__-VBE6LLEe-YhYlYVX9NAA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__-VBEaLLEe-YhYlYVX9NAA" x="1235" y="127"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pElMsKLMEe-YhYlYVX9NAA" type="3005" element="_pEjXgKLMEe-YhYlYVX9NAA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pElMsqLMEe-YhYlYVX9NAA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pElMsaLMEe-YhYlYVX9NAA" x="1334" y="124"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rqkXg6LMEe-YhYlYVX9NAA" type="3009" element="_rqjwcKLMEe-YhYlYVX9NAA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_rqkXhaLMEe-YhYlYVX9NAA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_rqk-kKLMEe-YhYlYVX9NAA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rqkXhKLMEe-YhYlYVX9NAA" x="1362" y="233"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-CvBrKLMEe-YhYlYVX9NAA" type="3005" element="_-CuakKLMEe-YhYlYVX9NAA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-CvBrqLMEe-YhYlYVX9NAA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-CvBraLMEe-YhYlYVX9NAA" x="1439" y="226"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__v5HA6LMEe-YhYlYVX9NAA" type="3009" element="__v4f8KLMEe-YhYlYVX9NAA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="__v5uEKLMEe-YhYlYVX9NAA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="__v5uEaLMEe-YhYlYVX9NAA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__v5HBKLMEe-YhYlYVX9NAA" x="1581" y="214"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_CUQhMKLNEe-YhYlYVX9NAA" type="3008" element="_CUP6IKLNEe-YhYlYVX9NAA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_CUQhMqLNEe-YhYlYVX9NAA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_CUQhM6LNEe-YhYlYVX9NAA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CUQhMaLNEe-YhYlYVX9NAA" x="1581" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rCM8sKLcEe-XR5i3qur68g" type="3005" element="_rCMVoKLcEe-XR5i3qur68g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rCM8saLcEe-XR5i3qur68g" type="5005" element="_rCMVoKLcEe-XR5i3qur68g"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rCM8sqLcEe-XR5i3qur68g" x="631" y="149" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_McgJAKELEe-aYLU-FfmCmw" type="3005" element="_Mcfh8KELEe-aYLU-FfmCmw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_McgJAqELEe-aYLU-FfmCmw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_McgJAaELEe-aYLU-FfmCmw" x="270" y="250" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_I3SgbKEMEe-aYLU-FfmCmw" type="3005" element="_I3R5UKEMEe-aYLU-FfmCmw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_I3SgbqEMEe-aYLU-FfmCmw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_I3SgbaEMEe-aYLU-FfmCmw" x="447" y="149" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-AZPUKN8Ee-prI0FBJ3d6g" type="3008" element="_-AYoQKN8Ee-prI0FBJ3d6g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_-AZPUqN8Ee-prI0FBJ3d6g" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_-AZPU6N8Ee-prI0FBJ3d6g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-AZPUaN8Ee-prI0FBJ3d6g" x="802" y="251"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ALXSE6N9Ee-prI0FBJ3d6g" type="3008" element="_ALWrAKN9Ee-prI0FBJ3d6g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ALXSFaN9Ee-prI0FBJ3d6g" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ALXSFqN9Ee-prI0FBJ3d6g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ALXSFKN9Ee-prI0FBJ3d6g" x="308" y="148"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eTTl_KOREe-prI0FBJ3d6g" type="3005" element="_eTS-4KOREe-prI0FBJ3d6g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eTTl_qOREe-prI0FBJ3d6g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eTTl_aOREe-prI0FBJ3d6g" x="882" y="358" width="149" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_kmxTYKQmEe-e_PUYJW9ZgA" type="3008" element="_kmqlsKQmEe-e_PUYJW9ZgA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_kmx6cKQmEe-e_PUYJW9ZgA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kmx6caQmEe-e_PUYJW9ZgA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kmxTYaQmEe-e_PUYJW9ZgA" x="935" y="258"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_q9tAQKQmEe-e_PUYJW9ZgA" type="3008" element="_q9sZMKQmEe-e_PUYJW9ZgA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_q9tAQqQmEe-e_PUYJW9ZgA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_q9tAQ6QmEe-e_PUYJW9ZgA" x="33" y="7"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_q9tAQaQmEe-e_PUYJW9ZgA" x="1087" y="258"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qVCQM6RGEe-hA-m3F63kgQ" type="3009" element="_qVBpIKRGEe-hA-m3F63kgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qVC3QKRGEe-hA-m3F63kgQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qVC3QaRGEe-hA-m3F63kgQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qVCQNKRGEe-hA-m3F63kgQ" x="1752" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xc3OgKRGEe-hA-m3F63kgQ" type="3005" element="_xc2ncKRGEe-hA-m3F63kgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xc3OgqRGEe-hA-m3F63kgQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xc3OgaRGEe-hA-m3F63kgQ" x="1842" y="208" width="161" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_31Gi8KRGEe-hA-m3F63kgQ" type="3009" element="_31F74KRGEe-hA-m3F63kgQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_31Gi8qRGEe-hA-m3F63kgQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_31Gi86RGEe-hA-m3F63kgQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_31Gi8aRGEe-hA-m3F63kgQ" x="2075" y="233"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4w9uSaRGEe-hA-m3F63kgQ" type="3027" element="_4w9uQKRGEe-hA-m3F63kgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4w-VUKRGEe-hA-m3F63kgQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4w9uSqRGEe-hA-m3F63kgQ" x="2037" y="100" width="130" height="64"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_lStKYaEHEe-aYLU-FfmCmw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_lStKYqEHEe-aYLU-FfmCmw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_lStKY6EHEe-aYLU-FfmCmw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_lStxcqEHEe-aYLU-FfmCmw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lStKZKEHEe-aYLU-FfmCmw" x="23" y="250" width="2118" height="495"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_m1ytwKEHEe-aYLU-FfmCmw" type="3007" element="_m1xfoKEHEe-aYLU-FfmCmw">
          <children xmi:type="notation:DecorationNode" xmi:id="_m1ytxaEHEe-aYLU-FfmCmw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_m1ytxqEHEe-aYLU-FfmCmw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_tiap-6LMEe-YhYlYVX9NAA" type="3005" element="_tiaC4KLMEe-YhYlYVX9NAA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tiap_aLMEe-YhYlYVX9NAA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tiap_KLMEe-YhYlYVX9NAA" x="1439" y="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rnNCsKRGEe-hA-m3F63kgQ" type="3005" element="_rnMboKRGEe-hA-m3F63kgQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rnNpwKRGEe-hA-m3F63kgQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rnNCsaRGEe-hA-m3F63kgQ" x="1828" y="68" width="175" height="87"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_m1ytwaEHEe-aYLU-FfmCmw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_m1ytwqEHEe-aYLU-FfmCmw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_m1ytw6EHEe-aYLU-FfmCmw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_m1ytx6EHEe-aYLU-FfmCmw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_m1ytxKEHEe-aYLU-FfmCmw" x="48" y="200" width="1297" height="250"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_g9_M4aEHEe-aYLU-FfmCmw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_g9_M4qEHEe-aYLU-FfmCmw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_g9_M46EHEe-aYLU-FfmCmw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_g9_z8qEHEe-aYLU-FfmCmw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_g9_M5KEHEe-aYLU-FfmCmw" width="2706" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_wa74zaEGEe-aYLU-FfmCmw"/>
    <edges xmi:type="notation:Connector" xmi:id="_g5DEoKHaEe-aYLU-FfmCmw" type="4001" element="_g5B2gKHaEe-aYLU-FfmCmw" source="_goWWMKHaEe-aYLU-FfmCmw" target="_u2cVA6EIEe-aYLU-FfmCmw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g5DrsKHaEe-aYLU-FfmCmw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g5DrsaHaEe-aYLU-FfmCmw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g5DEoaHaEe-aYLU-FfmCmw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g5DEoqHaEe-aYLU-FfmCmw" points="[-2, -5, -114, 7]$[103, -5, -9, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g5Fg4KHaEe-aYLU-FfmCmw" id="(1.0,0.8)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g5Fg4aHaEe-aYLU-FfmCmw" id="(0.09,0.44)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zzyJEKLGEe-pXblqnP0p3A" type="4001" element="_zzxiAKLGEe-pXblqnP0p3A" source="_u2cVA6EIEe-aYLU-FfmCmw" target="_vrGsLKEIEe-aYLU-FfmCmw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zzyJE6LGEe-pXblqnP0p3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zzyJFKLGEe-pXblqnP0p3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zzyJEaLGEe-pXblqnP0p3A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zzyJEqLGEe-pXblqnP0p3A" points="[-48, 24, 11, -130]$[-48, 124, 11, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zzzXMKLGEe-pXblqnP0p3A" id="(1.0,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_I28dA6LLEe-YhYlYVX9NAA" type="4001" element="_I28dAKLLEe-YhYlYVX9NAA" source="_I2zTEKLLEe-YhYlYVX9NAA" target="__-VBEKLLEe-YhYlYVX9NAA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_I29EEKLLEe-YhYlYVX9NAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_I29EEaLLEe-YhYlYVX9NAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_I28dBKLLEe-YhYlYVX9NAA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_I28dBaLLEe-YhYlYVX9NAA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__-XdUKLLEe-YhYlYVX9NAA" type="4001" element="__-W2QKLLEe-YhYlYVX9NAA" source="__-VBEKLLEe-YhYlYVX9NAA" target="_pElMsKLMEe-YhYlYVX9NAA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__-XdU6LLEe-YhYlYVX9NAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__-XdVKLLEe-YhYlYVX9NAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__-XdUaLLEe-YhYlYVX9NAA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__-XdUqLLEe-YhYlYVX9NAA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pEnB46LMEe-YhYlYVX9NAA" type="4001" element="_pEnB4KLMEe-YhYlYVX9NAA" source="_pElMsKLMEe-YhYlYVX9NAA" target="_rqkXg6LMEe-YhYlYVX9NAA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pEnB5qLMEe-YhYlYVX9NAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pEnB56LMEe-YhYlYVX9NAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pEnB5KLMEe-YhYlYVX9NAA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pEnB5aLMEe-YhYlYVX9NAA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rqmMs6LMEe-YhYlYVX9NAA" type="4001" element="_rqmMsKLMEe-YhYlYVX9NAA" source="_rqkXg6LMEe-YhYlYVX9NAA" target="_-CvBrKLMEe-YhYlYVX9NAA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rqmMtqLMEe-YhYlYVX9NAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rqmMt6LMEe-YhYlYVX9NAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rqmMtKLMEe-YhYlYVX9NAA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rqmMtaLMEe-YhYlYVX9NAA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7AQvIKLMEe-YhYlYVX9NAA" type="4001" element="_7AQIEKLMEe-YhYlYVX9NAA" source="_rqkXg6LMEe-YhYlYVX9NAA" target="_tiap-6LMEe-YhYlYVX9NAA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7AQvI6LMEe-YhYlYVX9NAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7AQvJKLMEe-YhYlYVX9NAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7AQvIaLMEe-YhYlYVX9NAA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7AQvIqLMEe-YhYlYVX9NAA" points="[-22, 16, -107, -138]$[-22, 176, -107, 22]$[34, 176, -51, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7AR9QKLMEe-YhYlYVX9NAA" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7AR9QaLMEe-YhYlYVX9NAA" id="(0.51,0.06)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-Cxd4KLMEe-YhYlYVX9NAA" type="4001" element="_-Cw20KLMEe-YhYlYVX9NAA" source="_-CvBrKLMEe-YhYlYVX9NAA" target="__v5HA6LMEe-YhYlYVX9NAA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-Cxd46LMEe-YhYlYVX9NAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-Cxd5KLMEe-YhYlYVX9NAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-Cxd4aLMEe-YhYlYVX9NAA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-Cxd4qLMEe-YhYlYVX9NAA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__v68M6LMEe-YhYlYVX9NAA" type="4001" element="__v68MKLMEe-YhYlYVX9NAA" source="__v5HA6LMEe-YhYlYVX9NAA" target="_CUQhMKLNEe-YhYlYVX9NAA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__v68NqLMEe-YhYlYVX9NAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__v68N6LMEe-YhYlYVX9NAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__v68NKLMEe-YhYlYVX9NAA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__v68NaLMEe-YhYlYVX9NAA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AGzyM6LNEe-YhYlYVX9NAA" type="4001" element="_AGzyMKLNEe-YhYlYVX9NAA" source="_tiap-6LMEe-YhYlYVX9NAA" target="__v5HA6LMEe-YhYlYVX9NAA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AG0ZQKLNEe-YhYlYVX9NAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AG0ZQaLNEe-YhYlYVX9NAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AGzyNKLNEe-YhYlYVX9NAA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AGzyNaLNEe-YhYlYVX9NAA" points="[0, 0, -63, 204]$[61, 0, -2, 204]$[61, -185, -2, 19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AG1AUKLNEe-YhYlYVX9NAA" id="(1.0,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CUSWY6LNEe-YhYlYVX9NAA" type="4001" element="_CUSWYKLNEe-YhYlYVX9NAA" source="_CUQhMKLNEe-YhYlYVX9NAA" target="_qVCQM6RGEe-hA-m3F63kgQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CUSWZqLNEe-YhYlYVX9NAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CUSWZ6LNEe-YhYlYVX9NAA" x="-89" y="301"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CUSWZKLNEe-YhYlYVX9NAA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CUSWZaLNEe-YhYlYVX9NAA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Fq6T8KLNEe-YhYlYVX9NAA" type="4001" element="_Fq3QoKLNEe-YhYlYVX9NAA" source="_CUQhMKLNEe-YhYlYVX9NAA" target="__-VBEKLLEe-YhYlYVX9NAA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Fq6T86LNEe-YhYlYVX9NAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Fq6T9KLNEe-YhYlYVX9NAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Fq6T8aLNEe-YhYlYVX9NAA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Fq6T8qLNEe-YhYlYVX9NAA" points="[-22, -26, 346, -80]$[-22, -32, 346, -86]$[-368, -32, 0, -86]$[-368, 33, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Fq67AKLNEe-YhYlYVX9NAA" id="(1.0,0.6046511627906976)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_N6sjY6LOEe-YhYlYVX9NAA" type="4001" element="_N6sjYKLOEe-YhYlYVX9NAA" source="_vrGsLKEIEe-aYLU-FfmCmw" target="_McgJAKELEe-aYLU-FfmCmw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_N6tKcaLOEe-YhYlYVX9NAA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_N6tKcqLOEe-YhYlYVX9NAA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_N6sjZKLOEe-YhYlYVX9NAA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_N6tKcKLOEe-YhYlYVX9NAA" points="[0, -1, -100, 19]$[32, -1, -68, 19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N6txgKLOEe-YhYlYVX9NAA" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_N6txgaLOEe-YhYlYVX9NAA" id="(0.5666666666666667,0.15)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sAd7wKLcEe-XR5i3qur68g" type="4001" element="_sAX1IKLcEe-XR5i3qur68g" source="_I3SgbKEMEe-aYLU-FfmCmw" target="_rCM8sKLcEe-XR5i3qur68g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sAei0KLcEe-XR5i3qur68g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sAei0aLcEe-XR5i3qur68g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sAd7waLcEe-XR5i3qur68g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sAd7wqLcEe-XR5i3qur68g" points="[-7, -27, 15, 212]$[8, -209, 30, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_sAgYAKLcEe-XR5i3qur68g" id="(1.0,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CY3ds6N4Ee-prI0FBJ3d6g" type="4001" element="_CY3dsKN4Ee-prI0FBJ3d6g" source="_rCM8sKLcEe-XR5i3qur68g" target="_-AZPUKN8Ee-prI0FBJ3d6g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CY4EwKN4Ee-prI0FBJ3d6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CY4EwaN4Ee-prI0FBJ3d6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CY3dtKN4Ee-prI0FBJ3d6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CY3dtaN4Ee-prI0FBJ3d6g" points="[0, 0, -72, -96]$[32, 0, -40, -96]$[32, 96, -40, 0]$[51, 96, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CY4r0KN4Ee-prI0FBJ3d6g" id="(1.0,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ALaVY6N9Ee-prI0FBJ3d6g" type="4001" element="_ALaVYKN9Ee-prI0FBJ3d6g" source="_ALXSE6N9Ee-prI0FBJ3d6g" target="_I3SgbKEMEe-aYLU-FfmCmw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ALa8cKN9Ee-prI0FBJ3d6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ALa8caN9Ee-prI0FBJ3d6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ALaVZKN9Ee-prI0FBJ3d6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ALaVZaN9Ee-prI0FBJ3d6g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AzzyIKN9Ee-prI0FBJ3d6g" type="4001" element="_AzuSkKN9Ee-prI0FBJ3d6g" source="_-AZPUKN8Ee-prI0FBJ3d6g" target="_ALXSE6N9Ee-prI0FBJ3d6g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Az0ZMKN9Ee-prI0FBJ3d6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Az0ZMaN9Ee-prI0FBJ3d6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AzzyIaN9Ee-prI0FBJ3d6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AzzyIqN9Ee-prI0FBJ3d6g" points="[-22, -28, 494, 82]$[-22, -179, 494, -69]$[-521, -179, -5, -69]$[-521, -127, -5, -17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Az1AQKN9Ee-prI0FBJ3d6g" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_x5-7QKQ5Ee-hA-m3F63kgQ" id="(0.6046511627906976,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_lwi68KOOEe-prI0FBJ3d6g" type="4001" element="_lwiT4KOOEe-prI0FBJ3d6g" source="_McgJAKELEe-aYLU-FfmCmw" target="_ALXSE6N9Ee-prI0FBJ3d6g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lwi686OOEe-prI0FBJ3d6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lwi69KOOEe-prI0FBJ3d6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lwi68aOOEe-prI0FBJ3d6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lwi68qOOEe-prI0FBJ3d6g" points="[-54, -29, 7, 81]$[-54, -95, 7, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lwkJEKOOEe-prI0FBJ3d6g" id="(0.5416666666666666,0.06666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_snjYUKQ5Ee-hA-m3F63kgQ" id="(0.5348837209302325,0.9069767441860465)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DIaz4KOPEe-prI0FBJ3d6g" type="4001" element="_DIaM0KOPEe-prI0FBJ3d6g" source="_eTTl_KOREe-prI0FBJ3d6g" target="_q9tAQKQmEe-e_PUYJW9ZgA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DIaz46OPEe-prI0FBJ3d6g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DIaz5KOPEe-prI0FBJ3d6g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DIaz4aOPEe-prI0FBJ3d6g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DIaz4qOPEe-prI0FBJ3d6g" points="[0, 0, -77, 124]$[76, 0, -1, 124]$[76, -104, -1, 20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DIba8KOPEe-prI0FBJ3d6g" id="(1.0,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_q9vcgKQmEe-e_PUYJW9ZgA" type="4001" element="_q9u1cKQmEe-e_PUYJW9ZgA" source="_q9tAQKQmEe-e_PUYJW9ZgA" target="_I2zTEKLLEe-YhYlYVX9NAA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_q9vcg6QmEe-e_PUYJW9ZgA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_q9vchKQmEe-e_PUYJW9ZgA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_q9vcgaQmEe-e_PUYJW9ZgA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_q9vcgqQmEe-e_PUYJW9ZgA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tKCU8KQmEe-e_PUYJW9ZgA" type="4001" element="_tJ9ccKQmEe-e_PUYJW9ZgA" source="_q9tAQKQmEe-e_PUYJW9ZgA" target="_kmxTYKQmEe-e_PUYJW9ZgA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tKC8AKQmEe-e_PUYJW9ZgA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tKC8AaQmEe-e_PUYJW9ZgA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tKCU8aQmEe-e_PUYJW9ZgA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tKCU8qQmEe-e_PUYJW9ZgA" points="[-43, -9, 131, -96]$[-174, -9, 0, -96]$[-174, 66, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tKEKIKQmEe-e_PUYJW9ZgA" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_b0z04KQuEe-e_PUYJW9ZgA" type="4001" element="_b0u8YKQuEe-e_PUYJW9ZgA" source="_-AZPUKN8Ee-prI0FBJ3d6g" target="_kmxTYKQmEe-e_PUYJW9ZgA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_b00b8KQuEe-e_PUYJW9ZgA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_b00b8aQuEe-e_PUYJW9ZgA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_b0z04aQuEe-e_PUYJW9ZgA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_b0z04qQuEe-e_PUYJW9ZgA" points="[-22, 16, -11, -99]$[-22, 104, -11, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_b01DAKQuEe-e_PUYJW9ZgA" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_b01DAaQuEe-e_PUYJW9ZgA" id="(0.20930232558139536,0.4186046511627907)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_g-NXoKQuEe-e_PUYJW9ZgA" type="4001" element="_g-MwkKQuEe-e_PUYJW9ZgA" source="_kmxTYKQmEe-e_PUYJW9ZgA" target="_eTTl_KOREe-prI0FBJ3d6g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g-NXo6QuEe-e_PUYJW9ZgA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g-NXpKQuEe-e_PUYJW9ZgA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g-NXoaQuEe-e_PUYJW9ZgA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g-NXoqQuEe-e_PUYJW9ZgA" points="[-23, 10, 53, -87]$[-23, 69, 53, -28]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g-N-sKQuEe-e_PUYJW9ZgA" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g-N-saQuEe-e_PUYJW9ZgA" id="(0.14,0.38)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vRAa8KRGEe-hA-m3F63kgQ" type="4001" element="_vQ_z4KRGEe-hA-m3F63kgQ" source="_qVCQM6RGEe-hA-m3F63kgQ" target="_rnNCsKRGEe-hA-m3F63kgQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vRAa86RGEe-hA-m3F63kgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vRAa9KRGEe-hA-m3F63kgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vRAa8aRGEe-hA-m3F63kgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vRAa8qRGEe-hA-m3F63kgQ" points="[-22, 19, -142, -495]$[-22, 521, -142, 7]$[33, 521, -87, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_vRBpEKRGEe-hA-m3F63kgQ" id="(1.0,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0kaOQKRGEe-hA-m3F63kgQ" type="4001" element="_0kZnMKRGEe-hA-m3F63kgQ" source="_qVCQM6RGEe-hA-m3F63kgQ" target="_xc3OgKRGEe-hA-m3F63kgQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0kaOQ6RGEe-hA-m3F63kgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0kaORKRGEe-hA-m3F63kgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0kaOQaRGEe-hA-m3F63kgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0kaOQqRGEe-hA-m3F63kgQ" points="[-3, -2, -131, -72]$[129, 47, 1, -23]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0ka1UKRGEe-hA-m3F63kgQ" id="(1.0,0.5581395348837209)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0ka1UaRGEe-hA-m3F63kgQ" id="(0.43478260869565216,0.225)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_31HKA6RGEe-hA-m3F63kgQ" type="4001" element="_31HKAKRGEe-hA-m3F63kgQ" source="_xc3OgKRGEe-hA-m3F63kgQ" target="_31Gi8KRGEe-hA-m3F63kgQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_31HKBqRGEe-hA-m3F63kgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_31HKB6RGEe-hA-m3F63kgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_31HKBKRGEe-hA-m3F63kgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_31HKBaRGEe-hA-m3F63kgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4On2MKRGEe-hA-m3F63kgQ" type="4001" element="_4OnPIKRGEe-hA-m3F63kgQ" source="_rnNCsKRGEe-hA-m3F63kgQ" target="_31Gi8KRGEe-hA-m3F63kgQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4On2M6RGEe-hA-m3F63kgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4On2NKRGEe-hA-m3F63kgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4On2MaRGEe-hA-m3F63kgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4On2MqRGEe-hA-m3F63kgQ" points="[0, 0, -164, 178]$[168, -155, 4, 23]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4OpEUKRGEe-hA-m3F63kgQ" id="(1.0,0.3103448275862069)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4w-VVKRGEe-hA-m3F63kgQ" type="4001" element="_4w-VUaRGEe-hA-m3F63kgQ" source="_31Gi8KRGEe-hA-m3F63kgQ" target="_4w9uSaRGEe-hA-m3F63kgQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4w-VV6RGEe-hA-m3F63kgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4w-VWKRGEe-hA-m3F63kgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4w-VVaRGEe-hA-m3F63kgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4w-VVqRGEe-hA-m3F63kgQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_60MxUKRGEe-hA-m3F63kgQ" type="4001" element="_60LjMKRGEe-hA-m3F63kgQ" source="_4w9uSaRGEe-hA-m3F63kgQ" target="_CDky8KKjEe-pXblqnP0p3A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_60MxU6RGEe-hA-m3F63kgQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_60MxVKRGEe-hA-m3F63kgQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_60MxUaRGEe-hA-m3F63kgQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_60MxUqRGEe-hA-m3F63kgQ" points="[0, 0, -259, -13]$[260, 25, 1, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_60NYYKRGEe-hA-m3F63kgQ" id="(1.0,0.359375)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_60NYYaRGEe-hA-m3F63kgQ" id="(0.13333333333333333,0.5333333333333333)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
